### PR TITLE
5.7.2 rework whole page

### PR DESCRIPTION
**Pull request by contentopx**

### CODE REVIEW

**Comment by rnathuji** [comment]
@contentopx , @mjoss17 - I was going to fix the validation error in this PR, but this seems like one of those that requires a judgement call which I don't want to make :joy: . Basically the error is due to the re-use of UUID `3bb9c5b7-0aef-4ece-bb21-17271f17303e` when a `os-raise-ib-input` was likely copied and then modified. However, glancing at this PR I am wondering if the original UUID should also be changed as the question is now different. :man_shrugging: I figure this might be a case in point of a scenario we mentioned in passing previously that the two of you might want to discuss.

In any case, while we're still in a mode where devs have to run a script to inject IDs, to avoid us having to try and make these decisions, I'd like to ask that content make edits until the validation errors are down to just `ERROR: Missing interactive block UUID` and any instances of `ERROR: Duplicate interactive block UUID` are addressed.

**Comment by contentopx** [comment]
I took out the duplicate UUID

**Comment by contentopx** [comment]
Just read ripal's comment...is the UUID tied to a specific question? Can we reassign?

**Comment by rnathuji** [comment]
I just updated the PR to correct the missing UUID errors. In terms of re-assigning or not, that's sort of a semantic question which I'll defer to you and @mjoss17 in terms of setting common expectations / conventions. I think in practice it comes down to:

* Are you **editing** an "existing question"? If so, keep the same ID
* Are you **replacing** an "existing question"? If so, remove the `data-content-id` attribute as part of the change. That will surface `ERROR: Missing interactive block UUID` and we'll generate a new one for it.

**Pull request merged**
